# site name
prefixName: Alexxxx
siteName: 
# favicon and site master avatar
favicon: /images/favicon.ico
avatar: https://al3xxxx.oss-cn-guangzhou.aliyuncs.com/img/20210513232724.png
url: https://github.com/al3xxxx
description: 只要祖国一声号令
timezone: Asia/Shanghai
#cdn: 
pjax: 1
# 1开启
mathjax: 0

notice: 等你好久了...
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    #随想: {path: /categories/随想/, fa: fa-commenting-o },
    技术: {path: /categories/技术/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    歌单: {path: /music/, fa: fa-headphones },
    #图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  #RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/al3xxxx/cdn@1.0/images/bg.jpg
  - https://cdn.jsdelivr.net/gh/al3xxxx/cdn@1.0/images/bg.jpg
  - https://cdn.jsdelivr.net/gh/al3xxxx/cdn@1.0/images/bg.jpg
  - https://cdn.jsdelivr.net/gh/al3xxxx/cdn@1.0/images/bg.jpg
  - https://cdn.jsdelivr.net/gh/al3xxxx/cdn@1.0/images/bg.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dim

# startdash url, title, desc img
startdash: 
  - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/startdash/sakura.md.png}
  - {url: https://steamcommunity.com/profiles/76561198146854576/, title: Steam, desc: 博主的Steam, img: https://al3xxxx.oss-cn-guangzhou.aliyuncs.com/img/20210328180148.jpg}
 # - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 26/03/2021

#social  url, img PC端配置
social:
  github: {url: https://github.com/al3xxxx, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/github.png}
 # sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=130265633, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wangyiyun.png}
 # zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
 # email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
  #wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}
  #wechat2: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/al3xxxx, fa: fa-github, color: 333}
 # weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
#  qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  alipay: https://al3xxxx.oss-cn-guangzhou.aliyuncs.com/img/20210327144144.jpg
  wechat: https://al3xxxx.oss-cn-guangzhou.aliyuncs.com/img/20210327144149.jpg
  wechatSQ: https://al3xxxx.oss-cn-guangzhou.aliyuncs.com/img/20210327144149.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 130265633
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: LucIU3FboReHoVjnz4NnAXcG-gzGzoHsz
v_appKey: uMDwNQxXDIuJ6iyRtUqDzAjz
v_verify: true
